# Generated by Django 4.2.17 on 2025-12-17 04:17

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Use __latest__ to ensure all Nautobot core migrations run first
        # This ensures models like Device, Interface, Platform exist before plugin migrations
        ('extras', '__latest__'),
        ('dcim', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('instance', models.IntegerField()),
                ('version', models.IntegerField(default=1)),
                ('template_text', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('is_validated', models.BooleanField(default=False, editable=False)),
                ('validation_message', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Config Template',
                'verbose_name_plural': 'Config Templates',
                'ordering': ['service', 'switch_profile', '-version'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ControlSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control Setting',
                'verbose_name_plural': 'Control Settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('mac_type', models.CharField(default='unknown', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('last_vlan', models.IntegerField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_interface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mac_address', to='dcim.interface')),
                ('last_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.device')),
                ('last_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.interface')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'MAC Address',
                'verbose_name_plural': 'MAC Addresses',
                'ordering': ['-last_seen'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Port Service',
                'verbose_name_plural': 'Port Services',
                'ordering': ['name'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('comm_room', models.CharField(blank=True, max_length=50)),
                ('jack', models.CharField(blank=True, max_length=50)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('attempted_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('previous_config', models.TextField(blank=True)),
                ('applied_config', models.TextField(blank=True)),
                ('requested_by', models.CharField(max_length=100)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dcim.location')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_queue_entries', to='dcim.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_queue_entries', to='dcim.interface')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_queue_entries', to='nautobot_network_provisioning.portservice')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_queue_entries', to='nautobot_network_provisioning.configtemplate')),
            ],
            options={
                'verbose_name': 'Work Queue Entry',
                'verbose_name_plural': 'Work Queue Entries',
                'ordering': ['-scheduled_time'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SwitchProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('device_type_pattern', models.CharField(max_length=100)),
                ('os_version_pattern', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=100)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_profiles', to='dcim.platform')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Switch Profile',
                'verbose_name_plural': 'Switch Profiles',
                'ordering': ['priority', 'name'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MACAddressHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(default='dynamic', max_length=20)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('sighting_count', models.IntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_history', to='dcim.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_history', to='dcim.interface')),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='nautobot_network_provisioning.macaddress')),
            ],
            options={
                'verbose_name': 'MAC Address History',
                'verbose_name_plural': 'MAC Address History',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='JackMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('comm_room', models.CharField(max_length=50)),
                ('jack', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jack_mappings', to='dcim.location')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jack_mappings', to='dcim.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jack_mapping', to='dcim.interface')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Jack Mapping',
                'verbose_name_plural': 'Jack Mappings',
                'ordering': ['building', 'comm_room', 'jack'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='configtemplate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='nautobot_network_provisioning.portservice'),
        ),
        migrations.AddField(
            model_name='configtemplate',
            name='switch_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='nautobot_network_provisioning.switchprofile'),
        ),
        migrations.AddField(
            model_name='configtemplate',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.CreateModel(
            name='ARPEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('vrf', models.CharField(blank=True, default='default', max_length=100)),
                ('entry_type', models.CharField(default='dynamic', max_length=20)),
                ('collected_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arp_entries', to='dcim.device')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arp_entries', to='dcim.interface')),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arp_entries', to='nautobot_network_provisioning.macaddress')),
            ],
            options={
                'verbose_name': 'ARP Entry',
                'verbose_name_plural': 'ARP Entries',
            },
        ),
        migrations.CreateModel(
            name='MACAddressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(default='dynamic', max_length=20)),
                ('collected_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_entries', to='dcim.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_entries', to='dcim.interface')),
                ('mac_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_entries', to='nautobot_network_provisioning.macaddress')),
            ],
            options={
                'verbose_name': 'MAC Address Entry',
                'verbose_name_plural': 'MAC Address Entries',
                'unique_together': {('mac_address', 'device', 'interface', 'vlan')},
            },
        ),
        migrations.AddConstraint(
            model_name='jackmapping',
            constraint=models.UniqueConstraint(fields=('interface',), name='unique_interface_jack_mapping'),
        ),
        migrations.AlterUniqueTogether(
            name='jackmapping',
            unique_together={('building', 'comm_room', 'jack')},
        ),
        migrations.AlterUniqueTogether(
            name='configtemplate',
            unique_together={('instance', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='arpentry',
            unique_together={('ip_address', 'device', 'vrf')},
        ),
    ]
