# Generated by Django 4.2.17 on 2025-12-25 13:22

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('extras', '0116_fix_dynamic_group_group_type_data_migration'),
        ('nautobot_network_provisioning', '0002_add_folder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(default='cli_config', max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('template_content', models.TextField(blank=True)),
                ('method_config', models.JSONField(blank=True, null=True)),
                ('logic_type', models.CharField(blank=True, max_length=50)),
                ('inherit_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inheritors', to='nautobot_network_provisioning.taskstrategy')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_strategies', to='dcim.platform')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Task Strategy',
                'verbose_name_plural': 'Task Strategies',
                'ordering': ['-priority', 'platform'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='taskintent',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Task Intent', 'verbose_name_plural': 'Task Intents'},
        ),
        migrations.AddField(
            model_name='taskintent',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taskintent',
            name='inputs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='taskintent',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskintent',
            name='rollback_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskintent',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taskintent',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskintent',
            name='validation_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationprovider',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automationproviderconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='extras.status'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_steps', to='extras.status'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='tags',
        ),
        migrations.AlterField(
            model_name='requestform',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskintent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskintent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='troubleshootingrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='troubleshootingrecord',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(on_delete=django.db.models.deletion.PROTECT, related_name='troubleshooting_records', to='extras.status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='TaskImplementation',
        ),
        migrations.AddField(
            model_name='taskstrategy',
            name='task_intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='nautobot_network_provisioning.taskintent'),
        ),
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='taskstrategy',
            unique_together={('task_intent', 'platform', 'method')},
        ),
        migrations.CreateModel(
            name='TaskImplementation',
            fields=[
            ],
            options={
                'verbose_name': '[Deprecated] Task Implementation',
                'verbose_name_plural': '[Deprecated] Task Implementations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nautobot_network_provisioning.taskstrategy',),
        ),
    ]
